name: example_cross_file_manager
description: An example for CrossFileManager.
homepage: https://github.com/signmotion/cross_file_manager

version: 0.3.0

publish_to: none

environment:
  flutter: ">=3.10.6"
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cross_file_manager:
    path: ../
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/1/
    - assets/1/deer/
    - assets/1/owl/
