name: example_cross_file_manager
description: An example for CrossFileManager.
homepage: https://github.com/signmotion/cross_file_manager

version: 0.1.0+100

publish_to: none

environment:
  flutter: '>=2.8.1 <3.0.0'
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cross_file_manager:
    path: ../
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/1/
    - assets/1/deer/
    - assets/1/owl/
