name: example_cross_file_manager
description: An example for CrossFileManager.
homepage: https://github.com/signmotion/cross_file_manager

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.4.2

publish_to: none

environment:
  flutter: ">=3.0.0 <4.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cross_file_manager:
    path: ../
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/1/
    - assets/1/deer/
    - assets/1/owl/
