name: cross_file_manager
description: >-
  Transparent reading of files from assets, Internet (by URL), zip archives by uploader priority.
repository: https://github.com/signmotion/cross_file_manager
topics:
  - files
  - cache
  - path
  - assets
  - archive

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.4.10

environment:
  flutter: ">=3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.5.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  #flutter_cache_manager_firebase: ^2.0.1
  path: ">=1.8.0 <3.0.0"
  path_provider: ^2.1.3
  stash: ^5.2.0
  stash_memory: ^5.2.0

dev_dependencies:
  flutter_lints: ^3.0.2
  lints: ^3.0.0
  test: ^1.25.2

screenshots:
  - description: "CrossFileManager demo"
    path: images/screenshots/zip_assets_demo.webp
