name: cross_file_manager
description: Transparent reading of files from assets, Internet (by URL), zip archives by uploader priority.
repository: https://github.com/signmotion/cross_file_manager

topics:
  - files
  - cache
  - path
  - assets
  - archive

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.4.4

environment:
  flutter: ">=3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.4.10
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  #flutter_cache_manager_firebase: ^2.0.1
  path: ">=1.8.0 <2.0.0"
  path_provider: ^2.1.2
  stash: ^5.0.3
  stash_memory: ^5.0.3

dev_dependencies:
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  test: ^1.25.2
