name: cross_file_manager
description: Can read files from assets, Internet (by URL), zip archives by loader priority.
homepage: https://github.com/signmotion/cross_file_manager

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.4.2

environment:
  flutter: ">=3.10.6"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.4.10

  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.3.0
  #flutter_cache_manager_firebase: ^2.0.1
  path: ^1.8.3
  path_provider: ^2.1.2
  stash: ^5.0.3
  stash_memory: ^5.0.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
