name: cross_file_manager
description: Can read files from assets, Internet (by URL), zip archives by loader priority.
homepage: https://github.com/signmotion/cross_file_manager

version: 0.1.0+100


environment:
  flutter: '>=2.10.0 <3.0.0'
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  archive: ^3.1.8
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_cache_manager_firebase: ^2.0.1
  path: ^1.8.0
  path_provider: ^2.0.8
  stash_memory: ^4.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
